// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://senusfhigkvqcnsymeqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbnVzZmhpZ2t2cWNuc3ltZXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDI3MzgsImV4cCI6MjA1NjkxODczOH0.6481lRzxWis-F7SgeV8TgInVdz5GVdWVVFLCZReoOH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);